//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ot_Sims_Givebox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discussion
    {
        public int Id { get; set; }
        public int OffreId { get; set; }
        public string Message { get; set; }
        public int UtilisateurId { get; set; }
        public System.DateTime DateMsg { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
