//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ot_Sims_Givebox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offre
    {
        public Offre()
        {
            this.EstArchivee = false;
            this.Fichier = new HashSet<Fichier>();
            this.Discussion = new HashSet<Discussion>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int Id { get; set; }
        public int UtilisateurId { get; set; }
        public string Titre { get; set; }
        public string Description { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public int CategorieId { get; set; }
        public string CodePostal { get; set; }
        public string Ville { get; set; }
        public bool EstArchivee { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual ICollection<Fichier> Fichier { get; set; }
        public virtual Categorie Categorie { get; set; }
        public virtual ICollection<Discussion> Discussion { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
